// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/about" | "/admin" | "/blog" | "/blog/[slug]" | "/booking" | "/contact" | "/dentmind" | "/dentmind/admin" | "/dentmind/dashboard" | "/faq" | "/gallery" | "/privacy-policy" | "/reviews" | "/treatments" | "/treatments/[slug]"
type AppRouteHandlerRoutes = "/api/admin/blogs" | "/api/admin/content" | "/api/admin/submissions" | "/api/ai/chat" | "/api/ai/report" | "/api/appointments" | "/api/contact"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/about": {}
  "/admin": {}
  "/api/admin/blogs": {}
  "/api/admin/content": {}
  "/api/admin/submissions": {}
  "/api/ai/chat": {}
  "/api/ai/report": {}
  "/api/appointments": {}
  "/api/contact": {}
  "/blog": {}
  "/blog/[slug]": { "slug": string; }
  "/booking": {}
  "/contact": {}
  "/dentmind": {}
  "/dentmind/admin": {}
  "/dentmind/dashboard": {}
  "/faq": {}
  "/gallery": {}
  "/privacy-policy": {}
  "/reviews": {}
  "/treatments": {}
  "/treatments/[slug]": { "slug": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
